name: Laravel CI/CD

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install additional PHP extensions
        run: |
          apt-get update
          apt-get install -y php8.0-pcov

      - name: Install dependencies
        run: |
          composer update
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Run npm
        run: npm run build

      - name: Prepare Laravel Application
        run: |
          rm .env.testing
          cp .env.ci .env
          php artisan key:generate

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/ --coverage-html coverage

      - name: Publish Code Coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/stin_bank
            git pull origin master
            composer install --no-interaction --no-ansi --no-progress --no-scripts --no-suggest
            php artisan migrate
            npm build
