name: Laravel CI

on:
  push:
    branches:
      - master
      - feature/ci_cd

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
          extensions: mbstring, pdo, pdo_mysql

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: |
           composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
           npm install

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Generate application key
        run: php artisan key:generate

      - name: Run npm
        run: npm run build

      - name: Migrate DB
        run: php artisan migrate:fresh --seed --force

      - name: Configure Test Environment
        run: php artisan config:clear

      - name: Run tests
        run: php artisan test

  deploy:
    needs: test
    if: startsWith(github.ref, 'refs/tags/deploy-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh <username>@<VPS-IP-Address> 'cd /path/to/your/app && git pull && composer install --no-interaction --no-ansi --no-progress --no-scripts --no-suggest && php artisan migrate --force && php artisan optimize'
